version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd library-recommendation-system
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: library-recommendation-system/dist
